# Generated by Django 3.1.7 on 2021-05-12 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(choices=[('Mateuszex', 'Mateuszex'), ('Piwkief', 'Piwkief'), ('Młody', 'Młody'), ('Prezes', 'Prezes'), ('Bogusław', 'Bogusław')], max_length=15)),
                ('lost', models.CharField(choices=[('Mateuszex', 'Mateuszex'), ('Piwkief', 'Piwkief'), ('Młody', 'Młody'), ('Prezes', 'Prezes'), ('Bogusław', 'Bogusław')], max_length=15)),
                ('winner_sets', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('lost_sets', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('duel_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(choices=[('Mateuszex', 'Mateuszex'), ('Piwkief', 'Piwkief'), ('Młody', 'Młody'), ('Prezes', 'Prezes'), ('Bogusław', 'Bogusław')], max_length=15)),
                ('matches', models.PositiveSmallIntegerField()),
                ('number_of_wins', models.PositiveSmallIntegerField()),
                ('number_of_lost', models.PositiveSmallIntegerField()),
                ('points', models.PositiveSmallIntegerField()),
                ('won_sets', models.PositiveSmallIntegerField()),
                ('lost_sets', models.PositiveSmallIntegerField()),
                ('set_ratio', models.SmallIntegerField()),
            ],
        ),
    ]
